version: "3"

services:
  myDB:
    image: postgres:15.3
    container_name: my-database
    restart: no
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=diego
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=mydatabase
    volumes:
      - ./postgres:/var/lib/postgresql/data
